os: linux
group: stable
dist: trusty
language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - bash <(curl -sL https://get.bpkg.sh)
  - bash <(curl -sL https://git.io/get-docker-compose)

script:
  - make docker-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
